# Solutions to task 1

In [2]:
import numpy as np

## a. Create a null vector of size 10 but the fifth value which is 1

In [4]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]



## b. Create a vector with values ranging from 10 to 49

In [6]:
b = np.arange(10,50)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## c. Reverse a vector (first element becomes last)

In [7]:
c = b[::-1]
print(c)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## d. Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
d = np.arange(0,9).reshape(3,3)
print(d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## e. Find indices of non-zero elements from [1,2,0,0,4,0]

In [44]:
# Create the array
e = np.array([1,2,0,0,4,0])
# Find where the nonzero elements are
e1 = np.where(e | 0)
print('The nonzeroe elements are at: ', e1[0])

The nonzeroe elements are at:  [0 1 4]


## f. Create a random vector of size 30 and find the mean value

In [28]:
f = np.random.rand(30)
print('The mena of the random vector is: ', f.mean())

The mena of the random vector is:  0.4310210361449646


## g. Create a 2d array with 1 on the border and 0 inside

In [35]:
# Choose the dimensions of the martix
xdim = 10
ydim = 5
# Create the matrix
g = np.zeros((ydim,xdim))
# Change the boarder values
g[0] = 1
g[-1] = 1
g[:,0] = 1
g[:,-1] = 1
# Print the results
print(g)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## h. Create a 8x8 matrix and fill it with a checkerboard pattern

In [49]:
# Create an zeros matrix
h = np.zeros((8,8), dtype=int)
# Set the value och every other element to 1 and shift over the rows
h[::2,::2] = 1
h[1::2,1::2] = 1
# Print the results
print(h)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


## i. Create a checkerboard 8x8 matrix using the tile function

In [50]:
i_cell = np.array([[0, 1], [1, 0]])
i = np.tile(i_cell,(4,4))
print(i)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## j. Given a 1D array, negate all elements which are between 3 and 8, in place

In [52]:
j = np.arange(11)
j[3:8] *= -1
print(j)

[ 0  1  2 -3 -4 -5 -6 -7  8  9 10]


## k. Create a random vector of size 10 and sort it

In [53]:
k = np.random.random(10)
k = np.sort(k)
print(k)

[0.01070833 0.04873588 0.10588514 0.10882478 0.35632964 0.36212406
 0.48643239 0.68994398 0.95789482 0.98129005]


## l. Consider two random array A anb B, check if they are equal

In [56]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = A == B
print(equal)

[False  True False  True False]


## m. How to convert an integer (32 bits) array into a float (32 bits) in place?

In [59]:
m = np.arange(10, dtype=np.int32)
print(m.dtype)
m = m.astype(np.float32)
print(m.dtype)

int32
float32


## n. How to get the diagonal of a dot product?

In [65]:
A = np.arange(9).reshape(3,3)
B = A + 1
C = np.dot(A,B)
D = C.diagonal()
print(C, ' has the diagonal ', D)

[[ 18  21  24]
 [ 54  66  78]
 [ 90 111 132]]  has the diagonal  [ 18  66 132]
